### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by ianic** [ianprime0509/pathological-packages#1]
I somehow found this yesterday and made a [test](https://github.com/ianic/zig/blob/f6c89282f68dfca58bbe576a3c1cb2995283d1c2/src/Package/Fetch.zig#L2039) to use it for the Fetch.zig development. 
Great work, thanks.

I'm trying to close [18080](https://github.com/ziglang/zig/issues/18089) so I [extended](https://github.com/ianic/zig/commit/6851b4b8170dcce00f6ad69ce92451a3683f502a) Fetch/git.zig to return diagnostic errors on file overwrite. Please review that commit if you have some time. Thanks.

**Comment by ianprime0509** [comment]
Nice work, thank you, @ianic! I'm glad this repository was helpful for your testing. I took a look at that commit and the rest of your branch and they look great to me. It looks like you found a good solution that preserves the separation of implementation that Andrew was asking for while still being quite readable and easy to understand.
